services:
  - type: web
    name: wa-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.mjs"   # <— CAMBIA AQUÍ
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
