services:
  - type: web
    name: wa-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node --experimental-default-type=module server.js"
    healthCheckPath: /health
